services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - media:/app/media
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=ED.settings
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 44.226.145.213:8000"
             
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
  media: